# Generated by Django 5.1.6 on 2025-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('ожидает', 'expected'), ('принята', 'accepted'), ('отклонена', 'rejected')], default='ожидает', max_length=50),
        ),
    ]
